# Generated by Django 5.2.3 on 2025-06-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
    ]
