# Generated by Django 5.2.3 on 2025-06-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_stock_product_id_stock_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
